[modules]
autoload = yes
noload = chan_skinny.so
noload = chan_phone.so
noload = chan_mgcp.so
noload = chan_iax2.so
load = chan_pjsip.so
load = res_pjsip.so
load = res_pjsip_pubsub.so
load = res_pjsip_session.so
load = res_pjsip_mwi.so
load = app_agi.so
